### ISSUE TITLE
Can not add form dynamically

### ISSUE THREAD

**Issue by kasulejoshua** [lane711/sonicjs#110]
@lane711 
i have a challenge, when i add a module with a form at the backend , it only shows content rendered by` <div>Hello to you {{ data.firstName }} from the formTest module!</div>` instead of loading the form itself, but when i look at your contact form it loads dynamically, was this hard coded, or it was a result of drag and drop from the form builder?

**Comment by lane711** [comment]
Hi, that is the default behavior as its the most common use case. For generating a form that users can submit, please check out how the contact module works here:
../sonicjs/server/modules/contact

Basically you need to use hooks to render the form:
` emitterService.on("postModuleGetData", async function (options) {
      if (options.shortcode.name !== "CONTACT") {
        return;
      }

      let contactFormSettingsId = options.shortcode.properties.id;

      options.viewModel.data.form = await formService.getForm(
        "contact",
        undefined,
        "submitForm(submission)",
        false,
        contactFormSettingsId,
        options.req.sessionID
      );

    });
`
Then your view simply renders the data.form like soL
`{{{ data.form }}}
`

You can definitely just copy the entire modules/contact folder and then rename the files and this file:

server/modules/contact/module.json

And then restart the application. This might be a good starting point for you.

HTH

**Comment by kasulejoshua** [comment]
@lane711 
Thanks for the response,
Regards
