### ISSUE TITLE
Error uuid4() Not found.

### ISSUE THREAD

**Issue by stefan1968** [lane711/sonicjs#112]
This happens when trying to register, after a fresh install.

Node version 15.3.0

This is a blocker to evaluating the product.

**Comment by kasulejoshua** [comment]
I also got this error, but i think the reason this is happening is, in the latest version there is no default user in the database, so what i did, i used an sqlite browser-->opened the database---> added an account, and i was able to proceed.
try it

**Comment by stefan1968** [comment]
Well, as a workaround it's ok, but this needs fixing urgently.

**Comment by lane711** [comment]
This is resolved in master. Thanks for letting me know!
