### ISSUE TITLE
Integrate ESlint/Prettier on the project

### ISSUE THREAD

**Issue by mandaputtra** [lane711/sonicjs#114]
There are many linting problems (unused variable, etc.) that I encounter on the codebase. I think adding ESLint (and or Prettier) for linter and formatting code would helpful. It also catches a silly issue like these #111.

I'm thinking of this strategy.

- Add ESLint/Prettier
- Make commit hooks using [husky](https://github.com/typicode/husky) so whenever we commit a code it will lint and fix it first
- Use [standard](https://standardjs.com/) code style (just my opinion)

Just let me know if this would be helpful for the project, I'll be working on it.

**Comment by lane711** [comment]
Hi @mandaputtra I 100% agree and would happily accept any PRs adding ESLint or both of them. I'm good with the standard code style. Husky automation would also be great. Thank you!

**Comment by lane711** [comment]
BTW - after doing any refactor or reformatting you can run the e2e cypress tests using `npm test` to smoke test the entire framework.
