### ISSUE TITLE
cpanel/shared hosting

### ISSUE THREAD

**Issue by xburnerr** [lane711/sonicjs#116]
Hi  tried to build this on cpanel hosted website of mine. Finally made it but now it connects to sonicjs home only by going non-  "https://" and also with port numbers included. Can I get any help on this subject thanks :)

also other than that checked out the panel and usage it seems pretty impressing.

**Comment by lane711** [comment]
Thanks for you feedback!

You can change the PORT setting to 80 or maybe 443 in your case in the .env file.

I'm not sure what is happening with Cpanel, but Sonic does have many deployments working under https including https://sonicjs.com/


HTH
