### ISSUE TITLE
Menu Issues

### ISSUE THREAD

**Issue by oppenheimer-** [lane711/sonicjs#121]
Just tried to follow the YT introductory videos and maybe catched a bug in the navigation.
It won't show nested menus at all and third levels don't render in the dropdown.

The example menu is set up like this
![image](https://user-images.githubusercontent.com/10992675/159035437-342b9a6f-fa52-4df1-bb82-89e6ff963a1e.png)

The source generated misses the third level
![image](https://user-images.githubusercontent.com/10992675/159035559-b31386fd-4968-4226-980e-1e77d7c5c9c9.png)

**Comment by lane711** [comment]
Third level nav is not currently implemented in the default menu. You can certainly add it yourself if it is a hard requirement. However third level navs are generally considered bad UX (which is why it is not part of Bootstrap 5 OOTB). HTH and thanks for trying SonicJS

**Comment by oppenheimer-** [comment]
Third level is indeed bad practice, what about the issue of the menu not showing at all? Is this supposed to be a CSS or JS drop-down?

**Comment by lane711** [comment]
Ah it looks like the markup is still in Bootstrap 4 markup, For Bootstrap 5, please trying changing data-toggle to data-bs-toggle per https://getbootstrap.com/docs/5.0/components/navbar/. If that works I would greatly appreciate a PR if you have the time. thx
