### ISSUE TITLE
Web Editor problems

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#129]
Hello I wanted to try out SonicJS but it seams that web editor is not working. basicly when pressing any of the buttons and content in their respective menus it seams like nothing is happening

![obraz](https://user-images.githubusercontent.com/51274570/176718308-6ca3227e-7fbc-478e-ad19-5c32a9b49398.png)

using docker with sql file DB. just copied latest beta release, builded it and launched...

**Comment by pietru2004** [comment]
using nodejs 16 LTS

**Comment by lane711** [comment]
thanks for reporting this. Are there any console or server errors?

To be clear, if you click on the purple module button, nothing happens right?

**Comment by pietru2004** [comment]
there are no errors other than on `npm install` saying about critical vulnerability and many high ones

and both purple and green button sub menus don't add anything to page but from what I seen some stuff apears in content menu after pressing show all

**Comment by pietru2004** [comment]
hm mayby it is cause I downloaded release which is 5.4 while version on page shows 5.5

**Comment by pietru2004** [comment]
well still not works
![obraz](https://user-images.githubusercontent.com/51274570/177210238-a2490333-d98f-440c-9e60-6b4caf175fc6.png)
I can show it via discord if there is one for sonicjs

**Comment by pietru2004** [comment]
Well I just looked into browser console and found this
![obraz](https://user-images.githubusercontent.com/51274570/177210592-6d3332da-2888-489c-8767-c004bf619434.png)

**Comment by pietru2004** [comment]
Moved to new issue with more errors
