### ISSUE TITLE
Errors from browser console - FrontEnd

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#130]
After my previous Issue I have been finding more warns/errors in console

![obraz](https://user-images.githubusercontent.com/51274570/177285421-5c499ae1-efe1-45b4-8759-34bf0f5ac994.png)

Here is error from page-builder 2 lines on top of screen are things I added when checking is the error occurring on line 662
![obraz](https://user-images.githubusercontent.com/51274570/177287241-11ca06a3-2076-495d-b20b-8bb5218106c5.png)
![obraz](https://user-images.githubusercontent.com/51274570/177287564-c6802942-04e3-4828-bf79-69109171e13a.png)

Page Builder on trying to delete section:
![obraz](https://user-images.githubusercontent.com/51274570/177289782-8b22d778-96ac-4f8c-a4fe-c04507f12bb6.png)

Translation of text on screen: `Blocked request to resource from another origin: rules „Same Origin Policy” don't allow to load remote resources from „http://localhost:3018/api-admin/roles” (failed CORS request). Status code: (null).`
![obraz](https://user-images.githubusercontent.com/51274570/177288554-b81b8103-601e-4b50-971a-9b3b2a2a0cf5.png)

Taxonomy Editor error on trying to add new blog category
![obraz](https://user-images.githubusercontent.com/51274570/177289093-81fa23c0-d8bb-4ada-a829-87b7b9ff033b.png)

**Comment by lane711** [comment]
There are currently some issues that occur when you are using a custom port. I plan to get these changes merged within the next couple of month. For now, if you are able to run on port 3018, it should provide a work-around

**Comment by pietru2004** [comment]
I had docker 3018 bound to 25599 since it was already open, will check it

**Comment by pietru2004** [comment]
checked and I have the same problem on localhost
![obraz](https://user-images.githubusercontent.com/51274570/177415867-406ccc33-f6ab-4b09-941d-bd2e15204c6e.png)

**Comment by pietru2004** [comment]
Seams it needs to use node 14 while my pc has node 16 so when logged to server via nomachine and used browser to go to localhost:3018 it works

![obraz](https://user-images.githubusercontent.com/51274570/177529702-af45350c-46fa-41cd-bbd1-62c0b1eeb92f.png)

but adding image seams broken and adding columns does not always work, mainly I could not add column until I added second row and first had item in it

**Comment by pietru2004** [comment]
By mistake removed message saying when I connect via nomachine and used browser from the server side it works to edit page
![obraz](https://user-images.githubusercontent.com/51274570/177610487-706e2ed6-84f1-4a4b-9cad-a2346f4d3ddb.png)

**Comment by lane711** [comment]
closing this and tracking on #142
