### ISSUE TITLE
Roles problems

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#132]
You can create new roles but there is no way to define permissions for the roles.

Also when you enter users panel and edit one you can't add them to user cause they don't show up in the panel.

**Comment by lane711** [comment]
Hi, permission management is currently in the works and should be merged in by the end of the month.

You should be able to assign roles to a user on the user screen. Are you saying you are unable to see or select roles? Are you using sonic on the default port 3018 locally?

**Comment by pietru2004** [comment]
no default port was not 3018 and it was not local but from server that was in local network

**Comment by pietru2004** [comment]
ok seams roles show on localhost(when using localhost on the server)
![obraz](https://user-images.githubusercontent.com/51274570/177528868-df09d524-8451-4ea9-b259-1a3a591e6aa8.png)

**Comment by lane711** [comment]
This is partially resolved in the current .6.0.0 release and will be further addressed in the upcoming releases.
