### ISSUE TITLE
Comunication question

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#133]
Could you maybe create sonic discord ? people could just join it and have "community" and dev support or share modules etc.

**Comment by pietru2004** [comment]
you can connect github to discord server from what I remember so any data from github would be send into a respective channel

**Comment by lane711** [comment]
Closing for now but will address this by adding a discord channel with the 1.0 release

**Comment by lane711** [comment]
@pietru2004 I am creating a new Discord server here: https://discord.gg/8bMy6bv3sZ

This can be used for anything SonicJs related. Thanks for the request
