### ISSUE TITLE
Module/Block sorting

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#134]
I think module/block menu

![obraz](https://user-images.githubusercontent.com/51274570/177530244-01ea8095-a9fe-461e-bdb7-8e0eae015ce7.png)

Should have things like Text, Button, Image, Video, Title and Header on top of the list cause they are most basic elements of the page and it is bit of pain to look through all the list to find 1 element such as text, and I am not sure why most of people would need `Compare CMS` block.

**Comment by lane711** [comment]
This is on my todo list - that ux need to be cleaned up quite a bit. thanks for reporting

**Comment by pietru2004** [comment]
It can be using types as blocks to be added with expandable option for module blocks under it
![obraz](https://user-images.githubusercontent.com/51274570/177610251-382fee27-668e-4ca0-9d96-65a964c4f7e9.png)
