### ISSUE TITLE
Object editing problem

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#135]
![obraz](https://user-images.githubusercontent.com/51274570/177609509-92fb7ab3-728a-48bc-a635-193782e4422c.png)
when you press on edit

It sends to this site
![obraz](https://user-images.githubusercontent.com/51274570/177609559-8bcb10f1-abd1-42b9-bae3-107463386244.png)
possible solution could be to store in cache last edited object for that module also I think page should not show id of page(IK 2 elements can have the same name)

it also problems when you click `role` hyperlink in roles edit screen
![obraz](https://user-images.githubusercontent.com/51274570/177609714-41dfb972-08e2-4541-8c6a-81aebd7a514b.png)
![obraz](https://user-images.githubusercontent.com/51274570/177609732-b7758691-65da-4589-a0d5-3803bb08957d.png)

This is followed by the same problem in users edit screen when clicking `User` hyperlink
![obraz](https://user-images.githubusercontent.com/51274570/177609946-6a78af09-cc41-4298-b122-478cb29388d9.png)
![obraz](https://user-images.githubusercontent.com/51274570/177609821-7b0a06e7-1601-4efc-afc2-58d5e6d1bc93.png)

**Comment by Turb0Dizel** [comment]
Hello.
Version sonicjs@0.5.5 start
I am also getting a similar error.

**Comment by lane711** [comment]
This should be resolved in current version >= 6.0.0
