### ISSUE TITLE
More account options

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#138]
I think it would be cool to be able to login via username that could be set in user panel + there could be ability to define custom profile fields, diagrams, switches etc.

<details>
<summary>This could be way to bigger flexibility of sonicjs cms usages.</summary>
Custom fields could on submit could send data to other app apis. Basicly devs could require user to create account via webpage and use that account to login for example to in game features and show statistics and data of user via webpage. It would make ability to create webpages that serve games for example that use webpage apis to store user data or auth them to the app.
</details>

**Comment by lane711** [comment]
Thanks for the feedback on many issues - Some of these will be addressed in an upcoming release that is in progress and the others will be on the roadmap

**Comment by lane711** [comment]
The user profile is just a content type and can be customized based on your needs. You can currently login with a username instead of email.
