### ISSUE TITLE
Adding Modules

### ISSUE THREAD

**Issue by Turb0Dizel** [lane711/sonicjs#140]
Hello.
Thank you very much for the SonicJs project.
Could you explain why ALL modules of the project are adding in the code on any page of the project?
I open the URL http://localhost:3018/404.
HTML code (Ctrl+U):
...
</script><script src="/modules/faq/assets/js/faq-module.js">
</script><script src="/modules/feature-box/assets/js/feature-box-module.js">
</script><script src="/modules/gallery/assets/js/gallery-module.js">
...
This is relevant for all project pages.
But I want my pages to be lightweight and not contain code that won't be used on the page.
How can I avoid this?
On another page (URL) I need the gallery-module.js module and I would like to include it.
Thanks in advance for your reply.

**Comment by lane711** [comment]
I agree this needs to be cleaned up and is in the short term road map. Thanks for you input
