### ISSUE TITLE
Using pictures from a module

### ISSUE THREAD

**Issue by Turb0Dizel** [lane711/sonicjs#141]
Hello.
sonicjs@0.5.5 start
I have created a new module.
I posted pictures to folder
C:\OpenServer\domains\sonicjs\server\modules\tetris\assets\img
But I couldn't use these pictures in the module.
I have tried various options for specifying the path:

server\modules\tetris\assets\img
modules\tetris\assets\img
tetris\assets\img
img

After that I loaded all the pictures in Media
http://localhost:3018/admin/media
Pictures managed to be used the path (CSS):
.turnLeft {
     background-image: url("/assets/uploads/rotateLeft.png");
}
Am I doing something wrong?
Or is the project not yet ready to use pictures from the module folder?

**Comment by lane711** [comment]
Please see the code here for how Sonic serves static assets:
https://github.com/lane711/sonicjs/blob/main/server.js#L254

Sonic does not currently support serving images from module folder, but I agree that is should. I'd happily approve a pull request if you would like to add it.

**Comment by Turb0Dizel** [comment]
This is logical.
When we create a new module, an img folder is created in the assets folder:
\sonicjs\server\modules\test1\assets\img

**Comment by lane711** [comment]
Closing issues related to the legacy version
