### ISSUE TITLE
Comunication

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#144]
Could there rl mayby be discord for Sonicjs?
It is possible to use [Webhooks](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks) to send events from github to selected channels.

Also you could enter voice chat and have people stream live issue to you.

Also could you try to send ending message to Issues? I personally have no idea have I done something wrong and made you angry/annoyed in https://github.com/lane711/sonicjs/issues/142 or did you just happen to get to know what is the issue and started fixing it.

I personally like concept of sonicjs, but that small communication things make me think is all alright - will it be working CMS outside of editing page localy.

**Comment by lane711** [comment]
Hi, I plan on setting up Discord once the project is near its 1.0 release. 

As far as issue #142, I had asked for info that was not yet provided. Please add as many details as you can or else it can be nearly impossible for me or others to reproduce the error that you are having.
