### ISSUE TITLE
Security of the project

### ISSUE THREAD

**Issue by Turb0Dizel** [lane711/sonicjs#146]
Hello
1) You couldn't consider changing
http://localhost:3018/admin
By moving the /admin URL to the project settings.

2) Set the number of failed authorization attempts in the project settings.

These simple steps will greatly increase the security of the project.
Thank you.

**Comment by lane711** [comment]
Hi, thanks - those are both items in the roadmap

**Comment by lane711** [comment]
Closing issues related to the legacy version
