### ISSUE TITLE
Can't use modules

### ISSUE THREAD

**Issue by Turb0Dizel** [lane711/sonicjs#148]
version 0.6.0
When adding any module, there is no data to fill in its parameters and the "Save" button.

![image](https://user-images.githubusercontent.com/29921918/188254859-777d6e95-a70a-410d-81d8-d6187d009919.png)

**Comment by pietru2004** [comment]
I have similar occurance but happens on certain modules - check blog and announcement - they seam to work

**Comment by lane711** [comment]
sorry guys this will be fixed soon - there is a major update in the works for the page builder
