### ISSUE TITLE
Outdated packages

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#150]
after `npm install` it shows this
![obraz](https://user-images.githubusercontent.com/51274570/188474836-4100667c-a4a6-45f1-bcb3-5f14214e7c22.png)

Is there possibility for those vulnerabilities to be patched(I mean package update)

**Comment by lane711** [comment]
yes, that is on my list. will do asap

**Comment by lane711** [comment]
Closing issues related to the legacy version
