### ISSUE TITLE
SonicJS Branches

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#152]
I have seen there are multiple sonic branches available and active, but could you do 1 to which it would auto merge or to which you would merge features more often? People can create multiple Issues to things that you have resolved but have been forgotten to be merged to a branch. Like it was with `feature/permissions` changes.

Something like **single** Beta/dev branch?

![obraz](https://user-images.githubusercontent.com/51274570/188492954-1e1f79c1-0e5b-4f15-afef-7b8a0caecc2c.png)

Not to mention countless stale branches

![obraz](https://user-images.githubusercontent.com/51274570/188493128-f9e4c102-6994-4ff2-9d8c-c562d6f0ac1f.png)

**Comment by lane711** [comment]
The branched will be cleaned up with release 1.0. There isn't currently enough activity to warrant a beta branch but that is certainly something that can be added when it makes sense.
