### ISSUE TITLE
Components not loading from server

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#153]
Text looks like this
![obraz](https://user-images.githubusercontent.com/51274570/188493625-f52ea2ba-fc1d-493e-b093-3508d7390e98.png)

Blog looks like this
![obraz](https://user-images.githubusercontent.com/51274570/188493686-d5aedb8d-cc2e-42f9-9d9f-e1688e9694ee.png)

It seams it could not fetch for some reason the Text components, I checked and it seams both Modules have components shown/set in modules settings, but text(+ button, tittle, html etc.) not in page builder form.

**Comment by lane711** [comment]
thanks, will address this soon and push out a fix

**Comment by lane711** [comment]
Closing issues related to the legacy version
