### ISSUE TITLE
Empty columns are visible outside of edditor - log off

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#154]
As shown on image empty columns show up - I think they should be invisible or be possible to be vanished

![obraz](https://user-images.githubusercontent.com/51274570/188494550-4a303fb4-6086-4dbe-9d7a-f11bf3d88a80.png)

![obraz](https://user-images.githubusercontent.com/51274570/188494654-f4619f53-867e-4afa-84c1-035278a735cc.png)

Simple fix could be to make color of text transparent
![obraz](https://user-images.githubusercontent.com/51274570/188494775-43bfce21-807f-4326-96e6-3207affc23be.png)

**Comment by lane711** [comment]
It should hide once you are in view mode but this will be updated anyway soon with an upcoming release
