### ISSUE TITLE
page builder testing

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#156]
IS it possible to pre test new page builder? if yes what steps would be needed ?

**Comment by lane711** [comment]
Its still fairly early in development to be alpha tested. In the upcoming weeks, I can let you know once its more in a beta state. Here is a preview of the new layout FWIW:
<img width="1678" alt="Screen Shot 2022-09-07 at 2 30 59 PM" src="https://user-images.githubusercontent.com/4350219/188985417-490e939a-22be-47a7-a06b-e7078de4b5ad.png">

**Comment by pietru2004** [comment]
Looks way cleaner, still there will be bugs... :)

As I look pls remember about IFrames - ex. game engines allow to compile for web and it would be handy to just pass link to iframe and have it display app.
