### ISSUE TITLE
Can't delete image

### ISSUE THREAD

**Issue by Turb0Dizel** [lane711/sonicjs#157]
Hello.
version 0.6.0
1. Media
2. Upload new image
3. Button Delete.
4. Npm log:

  code: 'MissingRequiredParameter',
  time: 2022-09-13T18:25:20.498Z
} MissingRequiredParameter: Missing required key 'Bucket' in params
    at ParamValidator.fail (c:\OpenServer\domains\sonicjs\node_modules\aws-sdk\lib\param_validator.js:50:37)
    at ParamValidator.validateStructure (c:\OpenServer\domains\sonicjs\node_modules\aws-sdk\lib\param_validator.js:61:14)

**Comment by lane711** [comment]
Hi, what is your FILE_STORAGE variable set to in your .env?

**Comment by Turb0Dizel** [comment]
FILE_STORAGE=FILE_SYSTEM
Default settings(I didn't change anything).
Re-downloaded Sonic 1 week ago.

![image](https://user-images.githubusercontent.com/29921918/190054063-9309e9d3-2a86-4b14-b94d-cc889c1a7614.png)

**Comment by lane711** [comment]
Closing issues related to the legacy version
