### ISSUE TITLE
Stronger colors

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#160]
I want to propose stronger colors for new webpage builder cause I checked it on older monitor and well
I have some problems reading GUI
![grays](https://user-images.githubusercontent.com/51274570/194704812-3e128fa0-115b-44a8-891c-ca618cad3933.jpg)

ex.
medium-grey from #d8d8d8 to #9d9d9d

**Comment by pietru2004** [comment]
Basicaly I have old monitor and I can't see a diffrence between editor buttons and background

**Comment by lane711** [comment]
Closing issues related to the legacy version
