### ISSUE TITLE
Singup problems

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#161]
When downloading and running
https://github.com/lane711/sonicjs/tree/feature/page-builder

It tells that admin account has been created when it is fresh download.

**Comment by lane711** [comment]
I'll clean that up before merge. In the meantime, you can use:
***@***.***
tiger44

HTH

**Comment by pietru2004** [comment]
well it is funny that mail got
![obraz](https://user-images.githubusercontent.com/51274570/195707490-a6a3ff09-88d2-4be7-8d9a-29fe929fbcf1.png)
I checked it with sqlitle viewer

**Comment by lane711** [comment]
ugh for email use:
a
@ 
a
.
c
o
m
