### ISSUE TITLE
Command Injection with growl

### ISSUE THREAD

**Issue by grasskin** [lane711/sonicjs#17]
**Describe the bug**
When clean-installing sonicjs from the repo npm warns of a critical security flaw with the growl version. Unfortunately it cannot be fixed automatically.

 Dependency of: loopback-component-storage
Path: loopback-component-storage > pkgcloud > liboneandone > mocha > growl

**Comment by lane711** [comment]
Thanks for submitting this. I plan on cleaning up any security issues before the official first release. As for growl, I don't believe it is used anymore so I will likely just remove it altogether.
