### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#170]
IS there way to hide buttons in footer?
![obraz](https://user-images.githubusercontent.com/51274570/200435289-0f9dc704-4edd-4090-91a9-9934c69875d3.png)
I tried setting custom footer but it did not work.

**Comment by lane711** [comment]
sure, you can the template:
server/themes/front-end/bootstrap5/theme.hbs

I will fix it so that it is driven off of the custom footer text setting

In a future release there will be a header and footer builder UI that will allow you to select and modify various header/footer styles

**Comment by pietru2004** [comment]
ok thanks :-)

**Comment by lane711** [comment]
the text is now driven from the footer text settings
