### ISSUE TITLE
Page Builder Glitch

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#175]
This might been fixed, but if not well

This is how it looks as admin - logged
![obraz](https://user-images.githubusercontent.com/51274570/206173053-5622560b-44c5-4b44-8567-a5473d868763.png)

And this is how it looks when not logged in
![obraz](https://user-images.githubusercontent.com/51274570/206172949-8d235d82-088c-4a08-91bd-19b97a51d266.png)

**Comment by lane711** [comment]
thanks for posting, I was able to reproduce this. I'll push out a fix asap today

**Comment by lane711** [comment]
This should be resolved on main, thx
