### ISSUE TITLE
Admin account already created error

### ISSUE THREAD

**Issue by andrejmoltok** [lane711/sonicjs#178]
Hello,

the problem is as sugegsted in the title of this issue.

I installed SonicJs as described in the docs and used `npm start` to start the server. When I wanted to register the admin account, nothing appeared, except for this error message: `Admin account already created`, when there wasn't any prompt to me that I could create the admin account.

Is there a fix for this somehow? I really want to use this CMS.

**Comment by lane711** [comment]
For now Use:
***@***.***
demo123

Sorry, will fix this ASAP

**Comment by andrejmoltok** [comment]
Thanks a lot, it worked.
