### ISSUE TITLE
demo.sonicjs.com is empty and docs don't works

### ISSUE THREAD

**Issue by jrichardsz** [lane711/sonicjs#182]
I tried to enter to https://demo.sonicjs.com/ but an empty page is rendered

![image](https://user-images.githubusercontent.com/3322836/235712055-306e452a-3b55-445b-b3d9-3e99f60b5827.png)

If I click into

![image](https://user-images.githubusercontent.com/3322836/235712166-fb5a00dd-fc43-4384-b708-fdb8424f4501.png)

The page is reloaded with same content

**Comment by lane711** [comment]
closing this as its the legacy version which is no longer being maintained. thx
