### ISSUE TITLE
Create a npx command for new project

### ISSUE THREAD

**Issue by lane711** [lane711/sonicjs#189]
This will replace the current getting started instructions, making it easier for developers to quick 

This will replace:
https://sonicjs.com/getting-started

**Comment by lukasbe** [comment]
Hi, I would like to work on that, if possible.

**Comment by lane711** [comment]
Hey @lukasbe of course! that would be great - please hit me up on discord if you have any questions along the way.

https://discord.gg/8bMy6bv3sZ
