### ISSUE TITLE
'rsync' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by appsdevpk** [lane711/sonicjs#198]
i was really excited when i came across sonicjs, i performed all the steps and in last step got the following error.
![image](https://github.com/lane711/sonicjs/assets/516860/cff3c06d-3979-41bb-9902-3657cc317b80)

**Comment by lane711** [comment]
Thanks for letting us know. This is probably a windows specific issue. I'll try installing on a windows machine and see how we can resolve this. 

It's happening because some of the scripts use rsync to copy files which isn't available on windows

**Comment by lane711** [comment]
Hey @appsdevpk , lt looks like I'm going to need to reconfigure esbuild to do the file copying and get rid of rsync. I'm planning on starting this asap next week. I'll keep you posted. thx for your patience.

**Comment by appsdevpk** [comment]
thanks @lane711 , no problem, i can wait

**Comment by lane711** [comment]
this has been resolved. I replaced rsync with https://www.npmjs.com/package/esbuild-plugin-copy
