### ISSUE TITLE
create-sonicjs-app readline error on Windows

### ISSUE THREAD

**Issue by lane711** [lane711/sonicjs#204]
need to research and fix this error on Windows that occurs when a user trys to install sonicjs with the npx command

<img width="599" alt="Screenshot 2023-08-22 at 11 52 44 AM" src="https://github.com/lane711/sonicjs/assets/4350219/9197f657-1d3f-4466-97bc-240cfcdffdfe">

The fix will likely be in this repo, but managing it here for visibility:
https://github.com/lane711/create-sonicjs-app

**Comment by osseonews** [comment]
Yeah, can't install this anymore anywhere. Keep getting this error: Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:readline/promises

Any fix for this???

**Comment by lane711** [comment]
SonicJs has been completely rewritten on top of Astro, so this issue should no longer be present.
