### ISSUE TITLE
Installation Process not clear

### ISSUE THREAD

**Issue by chrisspiegl** [lane711/sonicjs#212]
Dear @Lane711,

I just discovered SonicJS on the search for a headless edge CMS to integrate into my Nuxt.JS application.

This project seems to tick some boxes for me and I'm in the process of testing it out. Though I have found some info lacking in the process.

1. The D1 database name is hard coded (I tried setting it to something else but then the `pnpm run up` script didn't want to run cause it's referencing `sonicjs` as the D1 name directly.
2. The `npm run up` command is somewhere in the docs but not in the setup process. It also does not appear to run automatically after installation / setup / etc. so I had to do it manually as it seems.

Once I had adjusted the D1 name in the `package.json` file I was able to run `pnpm run up` and then start the dev server.

**Comment by lane711** [comment]
hey @chrisspiegl . Thanks for posting this. Did you use `npx create-sonicjs-app`?

**Comment by chrisspiegl** [comment]
I did use `pnpm` but yes, run the process through the guide. Though, I believe that my issues were with the aspect that I then also chose to customize some of the settings in the yarn file.

**Comment by lane711** [comment]
SonicJs has been completely rewritten on top of Astro, so this issue should no longer be present.
