### ISSUE TITLE
Installation Error: SonicJs Error: Error: D1_ERROR: no such table: users

### ISSUE THREAD

**Issue by mavichow** [lane711/sonicjs#222]
I've followed the installation step, filled in all the wrangler.toml via terminal eg: creating KV, Database, etc.

I gotten below error when I ran `npm run dev`

```
SonicJs Error: Error: D1_ERROR: no such table: users
Error: D1_ERROR: no such table: users
```

**Comment by lane711** [comment]
hey @mavichow this may be related to some code merged in yesterday. I'll look into this asap. Thanks for letting us know

**Comment by lane711** [comment]
Please try, stopping the server, then running:
`npm run up`

then restart with:
 `npm run dev`

This will run the migration scripts to populate the database.

**Comment by mavichow** [comment]
Thanks for the prompt reply!

Anyhow we still hitting this error after running `npm run up`

<img width="809" alt="Screenshot_2024-01-05_at_11_10_15_AM" src="https://github.com/lane711/sonicjs/assets/3140255/f37cf6f6-cebf-423c-9981-e5c34246962c">

Also i'm using node `v18.18.2`

**Comment by lane711** [comment]
that would indicate that the migrations were not successfully run when you executed `npm run up`. Can you share the output of the up command? 

You can also delete your local db to start over if that's easier. just delete the `.wrangler/state/v3/d1` folder
