### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by dm1001** [lane711/sonicjs#230]
Getting the following error with npm run up:

![image](https://github.com/lane711/sonicjs/assets/40149672/d91dabf6-08a2-4848-979d-846d61b88e30)

following error with npm run dev:

![image](https://github.com/lane711/sonicjs/assets/40149672/76ed1e56-4d87-4dab-a79c-83d2b859341a)

Was able to do prior steps successfully but cant seem to resolve these errors and cant get it up and running,

**Comment by dm1001** [comment]
Following is the wrangler log if it helps:


--- 2024-02-07T20:01:55.653Z debug
🪵  Writing logs to "C:\Users\WDAGUtilityAccount\AppData\Roaming\xdg.config\.wrangler\logs\wrangler-2024-02-07_20-01-55_466.log"
---

--- 2024-02-07T20:01:55.653Z debug
Failed to load .env file ".env": Error: ENOENT: no such file or directory, open 'C:\Users\WDAGUtilityAccount\sonicjs\.env'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:460:35)
    at tryLoadDotEnv (C:\Users\WDAGUtilityAccount\sonicjs\node_modules\wrangler\wrangler-dist\cli.js:124241:72)
    at loadDotEnv (C:\Users\WDAGUtilityAccount\sonicjs\node_modules\wrangler\wrangler-dist\cli.js:124250:12)
    at C:\Users\WDAGUtilityAccount\sonicjs\node_modules\wrangler\wrangler-dist\cli.js:162325:20
    at C:\Users\WDAGUtilityAccount\sonicjs\node_modules\wrangler\wrangler-dist\cli.js:131115:16
    at maybeAsyncResult (C:\Users\WDAGUtilityAccount\sonicjs\node_modules\wrangler\wrangler-dist\cli.js:129336:44)
    at C:\Users\WDAGUtilityAccount\sonicjs\node_modules\wrangler\wrangler-dist\cli.js:131114:14
    at C:\Users\WDAGUtilityAccount\sonicjs\node_modules\wrangler\wrangler-dist\cli.js:129323:22
    at Array.reduce (<anonymous>) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\WDAGUtilityAccount\\sonicjs\\.env'
}
---

--- 2024-02-07T20:01:56.217Z log
 ⛅️ wrangler 3.25.0 (update available [32m3.27.0[39m)
[38;2;255;136;0m-------------------------------------------------------[39m
---

**Comment by lane711** [comment]
Hi, did you create your app via the `npx create-sonicjs-app` command or from cloning the repo?

**Comment by dm1001** [comment]
I used npx create-sonicjs-app

**Comment by lane711** [comment]
looks like a wrangler related error - I haven't seen it before. Have you tried googling it? It could be permissions related on your local directory but that's just a guess

**Comment by dm1001** [comment]
Yes, found a just few references to it but no solution. I also updated wrangler to latest version but it made no difference. Getting that exact same error every time. I am able to run other wrangler commands no problem like for example wrangler kv:namespace create sonicjs... but no luck with npm run up and npm run dev unfortunately.

**Comment by dm1001** [comment]
Same problem when using the manual installation approach

**Comment by lane711** [comment]
are you able to create and run a basic hono app? This is what SonicJs is built on:
`npm create hono@latest ./my-app -- --template cloudflare-pages`

**Comment by dm1001** [comment]
That appears to work fine, see screenshot
![image](https://github.com/lane711/sonicjs/assets/40149672/6b4b0cc7-1400-4984-b920-0ade8cef543e)
Let me know if there is anything else I can try here. Thanks for your help.

**Comment by lane711** [comment]
SonicJs has been completely rewritten on top of Astro, so this issue should no longer be present.
