### ISSUE TITLE
Migrate D1 in production adjustment

### ISSUE THREAD

**Issue by ninjasitm** [lane711/sonicjs#246]
Hello,

Just came across this issue trying to update my production schema. 

In `package.json` the `up:prod` command runs: `wrangler d1 migrations apply sonicjs`/

This will not, as far as I can tell update your production database, only the local DB.

According to https://developers.cloudflare.com/workers/wrangler/commands/#migrations-apply there is a `--remote` switch that is needed to update the production/remote D1 DB.

# Recommendation

Update the `up:prod` command to use:

```
wrangler d1 migrations apply sonicjs --remote
```

Change the `up` command to, as `--local` is true by default:

```
wrangler d1 migrations apply sonicjs
```

**Comment by lane711** [comment]
SonicJs has been completely rewritten on top of Astro, so this issue should no longer be present.
