### ISSUE TITLE
Is there no hot reload feature?

### ISSUE THREAD

**Issue by LBC000** [lane711/sonicjs#257]
Is there no hot reload feature? How can I see the modified UI and API in real time? Having a hot reload feature would increase development efficiency.

**Comment by LBC000** [comment]
add nodemon.json for root
```json
{
  "watch": [
    "src",
    "public"
  ],
  "ext": "js,ts,mjs,cjs,json",
  "exec": "npm run dev"
}
```
npx nodemon

**Comment by lane711** [comment]
SonicJs has been completely rewritten on top of Astro, so this issue should no longer be present.

Hotload is now working
