### ISSUE TITLE
Why not just have 'category' as a field in the Post model?

### ISSUE THREAD

**Issue by davidwilliford99** [lane711/sonicjs#258]
I'm using SonicJS for a blog. I need the client to understand how to use it. It's difficult and cumbersome to add a category to a post, especially for someone not in a tech related career. Why not just have a dropdown or even a string input called 'category' in the posts model? Then we can just ignore the whole categories-to-posts relation. I will look into this, and if I find a solution I would love to send a pull request.

**Comment by lane711** [comment]
Hi David, you could update the schema to operate that way(the default blog schema is really just an example), but the UI doesn't currently have a way to display options in a select list, although this is certainly in the roadmap
