### ISSUE TITLE
Fresh deployment create user is broken

### ISSUE THREAD

**Issue by OultimoCoder** [lane711/sonicjs#261]
Fresh deployment with status showing everything ok.

If I create a user I immediately cannot login. I check D1 and password is set to null in the users table. 

What can I do? I delete k/v key, user data and user_key data and try again but the same result each time.

I tried copying the hashed password from user_keys into the user password field but it had no effect.

**Comment by OultimoCoder** [comment]
The issue is setting AUTH_KDF = scrypt, removing this env var fixes everything.

**Comment by lane711** [comment]
Thanks for posting the solution. We're in the process of converting Lucia Auth from 2 to version 3 and will check this to prevent it from occurring to anyone else

**Comment by OultimoCoder** [comment]
Thanks!
