### ISSUE TITLE
ERROR: "dev:wrangler" exited with 7. Following the guide on Windows 11

### ISSUE THREAD

**Issue by tecnicosya** [lane711/sonicjs#264]
Hi, I'm installing SonicJS in my first time and have stuck in this error:

npm run dev

> sonicjs@0.0.3 dev
> run-p dev:*

> sonicjs@0.0.3 dev:wrangler
> wrangler pages dev dist --env development --port 8786

> sonicjs@0.0.3 dev:esbuild
> node ./src/cms/util/build.mjs

▲ [WARNING] No compatibility_date was specified. Using today's date: 2024-10-19.

  Pass it in your terminal:
  ```
  --compatibility-date=2024-10-19
  ```
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more information.

✨ Compiled Worker successfully
 ⛅️ wrangler 3.25.0 (update available 3.81.0)
-------------------------------------------------------
Your worker has access to the following bindings:
- KV Namespaces:
  - KVDATA: 0892709136f34f3694414c9a78ce518c
- D1 Databases:
  - D1DATA: sonicjs (c9edf960-0f8a-4821-a85e-25dc84bc660f)
- R2 Buckets:
  - R2STORAGE: sonicjs
[wrangler:inf] Ready on http://127.0.0.1:8786
⎔ Starting local server...
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [c] clear console, [x] to exit                                                                                                         │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
C:\Users\jose\Documents\Desarrollo\web\backend\sonicjs\node_modules\wrangler\wrangler-dist\cli.js:29572
            throw a;
            ^

TypeError [ERR_INVALID_ARG_TYPE]: The "strategy" argument must be of type object. Received type number (0)
    at new ReadableStream (node:internal/webstreams/readablestream:254:5)
    at safeReadableStreamFrom (C:\Users\jose\Documents\Desarrollo\web\backend\sonicjs\node_modules\miniflare\dist\src\index.js:8418:10)
    at #handleLoopback (C:\Users\jose\Documents\Desarrollo\web\backend\sonicjs\node_modules\miniflare\dist\src\index.js:8580:36)
    at Server.emit (node:events:531:35)
    at Server.emit (node:domain:488:12)
    at parserOnIncoming (node:_http_server:1141:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.18.0
ERROR: "dev:wrangler" exited with 7.

**Comment by tecnicosya** [comment]
I update the wrangler version installed global and have the lasted, but if check in the project folder say older version.
I run:
npm install wrangler@latest

If I get this error:
npm run dev

> sonicjs@0.0.3 dev
> run-p dev:*


> sonicjs@0.0.3 dev:wrangler
> wrangler pages dev dist --env development --port 8786


> sonicjs@0.0.3 dev:esbuild
> node ./src/cms/util/build.mjs


 ⛅️ wrangler 3.81.0
-------------------


X [ERROR] Pages does not support targeting an environment with the --env flag. Use the --branch flag to target your production or preview branch


🪵  Logs were written to "C:\Users\jose\AppData\Roaming\xdg.config\.wrangler\logs\wrangler-2024-10-19_02-38-26_858.log"
ERROR: "dev:wrangler" exited with 1.

**Comment by tecnicosya** [comment]
with this line now SonicJS is running:
wrangler pages dev dist development --port 8786

**Comment by lane711** [comment]
SonicJs has been completely rewritten on top of Astro, so this issue should no longer be present.
