### ISSUE TITLE
 Installation Error: SonicJs Error: Error: D1_ERROR: no such table: users

### ISSUE THREAD

**Issue by TeeWallz** [lane711/sonicjs#265]
Hi,

I tripped up on the same error as #222 

This was due the Sonic setup script `npx create-sonicjs-app` advising the below after installation:

`SonicJS is setup successfully 🚀 To get started: cd sonicjs, npm run dev`

In #222, the fix was to run `npm run up` as per the README.md. However this command is not present in the output after running the script.

Could this extra step be added into the output after `npx create-sonicjs-app`  to align the README and create-sonicjs-app?

Thank you

**Comment by lane711** [comment]
SonicJs has been completely rewritten on top of Astro, so this issue should no longer be present.
