### ISSUE TITLE
site-settings-colors causing 504 gateway timeout

### ISSUE THREAD

**Issue by un-fuf-a-doo** [lane711/sonicjs#27]
**Describe the bug**
First. Thank-you for creating this. My buddy and I are trying to re-invent our site while learning node and Sonicjs gives us just the base we need.  Anyway, onto the bug:  On a fresh install simply going to the site-settings-colors link times out.

**To Reproduce**
1. Fresh install
2. Login as admin
3. Visit /admin
4. Try to visit site-settings-colors and see the below error in the console:

```
UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'editForm' of undefined
    at /opt/sonicjs/server/boot/routes.js:598:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Line number 598 correlates to the site-settings-colors route.

**Expected behavior**
I would expect the site-settings-colors page to load.

**Screenshots**
<img width="339" alt="Screen Shot 2020-09-30 at 8 14 23 PM" src="https://user-images.githubusercontent.com/67521579/94755264-90213480-0359-11eb-85f8-7c1c55232591.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: latest

**Smartphone (please complete the following information):**
 - NA

**Additional context**
There was another error saying chart.js files could not be found and that is because they capitalized the 'C' in the name of the files.  I symlinked them to a lowercase 'c' name and resolved that.

**Comment by lane711** [comment]
Hi, thanks for letting me know. This will be fixed in the next couple of days and I'll ping you back here to let you know.

Otherwise how is SonicJs working out for you?

Lane

**Comment by un-fuf-a-doo** [comment]
Hi Lane,

Sonic is pretty awesome for what we need. We are still learning NodeJS, and Sonic is one key in this effort because we learned how things can be structured and how things actually work.  I don't use the word "neat" very often, but this is all very neat. I love how things just fit together with just a little coding and allows us to focus on the content.

We are old school geeks learning an old school tech in a new school way.  If that makes sense.

Jeff

**Comment by lane711** [comment]
Hey Jeff, the above issue should be resolved if you get latest on master. Thanks for your feedback!
