### ISSUE TITLE
Fix media css layout

### ISSUE THREAD

**Issue by maheraldous** [lane711/sonicjs#29]
After uploading an image or more I can't touch them becuase of the layout see here:

#30 

https://prnt.sc/uwtkg2 fix it by write height: auto instead of 100px
![9](https://user-images.githubusercontent.com/41970874/95663150-e867eb80-0b3c-11eb-80c7-0ca9d5d42876.PNG)

**Comment by lane711** [comment]
Thanks for submitting this, will look into asap

**Comment by lane711** [comment]
Thanks again - this have been fixed and updated on master

**Comment by maheraldous** [comment]
> Thanks again - this have been fixed and updated on master

You are welcome. I will submit some nice style for you to make the Admin UI more beautiful.
