### ISSUE TITLE
Session Issue

### ISSUE THREAD

**Issue by maheraldous** [lane711/sonicjs#31]
Hello @lane711 
I was testing the CMS on localhost and after a while when I am working and want to refresh the page it log me out and when I hit to `http://localhost:3018/admin/` I can see that I am still loged in but in the other part of the website ex. `http://localhost:3018/admin/content-types/edit/hello-world` I am loged out and it redirect me back to `http://localhost:3018/`

When I go to `http://localhost:3018/register` it give me 404 page.

**Comment by lane711** [comment]
Hi, I'm not able to reproduce this, but if your admin session has expired, all admin routes (ie: http://locahost:3018/admin/...) should show the login page. 

the /register page is only for a brand new sites when you are creating your first admin user.

**Comment by maheraldous** [comment]
> Hi, I'm not able to reproduce this, but if your admin session has expired, all admin routes (ie: http://locahost:3018/admin/...) should show the login page.
> 
> the /register page is only for a brand new site when you are creating your first admin user.

Yes, I know it is for the new sites but I created the new site and after one day I started the site again to work but it took me again to create another user. Before I create another user I looked at the MongoDB and the admin user was there so I restarted the website again with CLI and it worked but it happen again sometimes. It solves itself by restarting the website.

**Comment by lane711** [comment]
ok, thx for the additional info, will look into this.

**Comment by lane711** [comment]
Hi, can you please tell me the user id created for you admin user? It should be 1, but if not, there would likely be problems

**Comment by maheraldous** [comment]
Sorry for late replay. In the MongoDB I have this.
![10](https://user-images.githubusercontent.com/41970874/96306337-c6b8a980-0fff-11eb-8cb4-2d49fb71f6cc.PNG)

**Comment by lane711** [comment]
Thanks, I think I see the issue, will fix this next week. Have a great weekend

**Comment by maheraldous** [comment]
> Thanks, I think I see the issue, will fix this next week. Have a great weekend

Thanks for you too, I think you can close this issue then. Have a great weekend too :).

**Comment by lane711** [comment]
This has been resolved on master, thanks
