### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Wemago** [lane711/sonicjs#32]
Can't get it to work. 
I've installed it using the process you have on your site for local setup.

It gave me this error
`Error: Cannot create data source "storage":`

and made me install
`npm install loopback-component-storage --save`
To fix it. 

After that the server starts but it's always restarting with nodemon saying that there was changes when I didn't do anything.

**Comment by lane711** [comment]
Hi Wemago, do you have any idea what file(s) might be getting created/updated to cause the restart? I haven't seen that issue before. 

Can you confirm that your .env file was created? It should be in the root directory

Thanks,
Lane
