### ISSUE TITLE
First start dev server

### ISSUE THREAD

**Issue by bypy** [lane711/sonicjs#34]
**Nodemon continiously restarting due to changes**

"name": "sonicjs-cms",
 "version": "0.2.0"

Website at:  http://localhost:3018
Admin console at:  http://localhost:3018/admin
REST API at:  http://localhost:3018/explorer
[nodemon] restarting due to changes...
[nodemon] starting `node server/server.js`
**regen template css**

**To Reproduce**
1. npm install
2. npm run setup -> flat file
3. npm start
4. and thats it..

**Desktop:**
 - OS: WIN 10 x64 build 19041.630
- Node.js: v12.0.0

**Comment by StratISaurus** [comment]
Also experiencing the same issue.
OS: Windows 10 x64 
Node.js v14 current LTS

Also running the flat file setup.

Confirmed that my .env file generated:

#dev or production
MODE=dev

FRONT_END_THEME=bootstrap

#check https://bootswatch.com/ for options
FRONT_END_THEME_BOOTSWATCH=lux

ADMIN_THEME=light

RECAPTCHA_SITE_KEY=CHANGEME

SENDGRID_API_KEY=CHANGEME
SENDGRID_PASSWORD=CHANGEME
SENDGRID_USERNAME=CHANGEME

AMAZONKEY=CHANGEME+cr32mvAE
AMAZONKEYID=CHANGEME

RUN_NEW_SITE_MIGRATION=TRUE

#Rebuild css/js assets, when mode set to production. After assets are rebuilt, this flag will be programatically set to FALSE
REBUILD_ASSETS=TRUE

**Comment by lane711** [comment]
Thanks for reporting this. I'm working on a major rework of the startup setup that should address this. I'll keep you posted once it is merged to master

**Comment by amacmill** [comment]
Any update on the rework?

**Comment by lane711** [comment]
Sure, it is still in the works, many new feature added as well. Best guess is that it will be ready for merge in mid February

**Comment by amacmill** [comment]
If you need any tester etc let me know.

**Comment by lane711** [comment]
Rework is complete, this issue is now resolved.

Thank you
