### ISSUE TITLE
lot of deprecated npm

### ISSUE THREAD

**Issue by fturiot** [lane711/sonicjs#36]
Lot of deprecated modules
exemple :
npm WARN deprecated sortablejs@1.12.0: Object.assign was not transformed during the build of sortablejs, so it won't work in browsers where this does not exist (for example IE11). Please downgrade your version to 1.10.2 to keep supporting <=IE11 or upgrade to >2.0 where IE will no longer be supported.
npm WARN deprecated tooltip.js@1.3.3: Tooltip.js is not supported anymore, please migrate to tippy.js
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated swagger-ui@2.2.10: No longer maintained,

i test to update all and use node 14

**Comment by lane711** [comment]
thx fturiot, this will be addressed in an uncoming release
