### ISSUE TITLE
Changes triggering infinitely 

### ISSUE THREAD

**Issue by garthtee** [lane711/sonicjs#43]
Love the project!

When I try to setup this project for the first time I run into changes being reported and restarting of the server infinitely.

I saw you're rewriting the setup of the project, but I thought I'd report this anyway. Hope it helps!

**To Reproduce**
Using node version 14.15.4 or 12.8.0 (as I just seen the max allowed node version)

1. npm install
2. npm run setup (flat file option chosen for database)
3. npm start

**Expected behavior**
Project works in the browser, I think the reason it's failing is that it's always restarting.

**Screenshots**
The output of continuous reloading of the css file:
![image](https://user-images.githubusercontent.com/15220832/107854981-93ecb980-6e17-11eb-9a30-145419c678c9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by lane711** [comment]
Please pull from master, this should be resolved. thank you
