### ISSUE TITLE
Convert from Bootstrap 4 to 5

### ISSUE THREAD

**Issue by lane711** [lane711/sonicjs#48]
Update npm packages. Will likely need to update the CoreUI admin theme as well

**Comment by CrazyOptimist** [comment]
Great work @lane711 !
Bootstrap 5 is cool.
The most important thing is to be stable for long run, in my personal opinion.
Hope your project goes well and get success over decades.
Added a star on your project.
Kind regards.

**Comment by lane711** [comment]
Bootstrap 5 is now supported in SonicJs! The default theme when you first install SonicJs will now use the default Bootstrap 5 template which can easily be copied and customized to you heart's content!
