### ISSUE TITLE
Issues with initial Setup

### ISSUE THREAD

**Issue by AleskiWeb** [lane711/sonicjs#65]
After running through the steps, when I run `npm run start` all looks well.

- I create the admin account using "signup"
- I use "test@test.com" and pw "1234" as im testing this project locally
- I am then presented with the login screen
- When i try and login with that username and password I am redirected to `localhost:3018/undefined`
- When going back to `localhost:3018` it does seem like I am logged in as an admin.
- Nearly every interaction with the admin UI gives me: the following:
```
EMIT ERROR: TypeError: Cannot read property 'data' of undefined
    at Object.functionToExecute (sonicjs\server\modules\page-templates\services\page-templates-main-service.js:96:41)
```

Do you have an option to use a specific data storage system instead of it recognising that I have mongo running and just connecting to that? I wanted to try and work around the issue above by using flat file instead but it will just always use mongo if its running.

**Comment by lane711** [comment]
Hi, Sorry the the issues. SonicJs no longer supports flat files. 

I've updated the readme to ensure that you validate the mongodb url before running the setup. Please try again with a fresh install following the latest README.md. Here is the part you need:

1. Clone the repo: `git clone https://github.com/lane711/sonicjs.git`
1. Change to created folder `cd sonicjs`
1. Validate the MONGODB_URL value the .env-default file (located in the root directory) 
1. Install the dependencies: `npm install`
1. Run it with: `npm start`

Please let me know if that resolves the issue

**Comment by AleskiWeb** [comment]
It is valid, would any of the above I mentioned even work if it wasnt valid?

**Comment by lane711** [comment]
When you run `npm start`, do you see the following in your terminal?

Website at:  http://localhost:3018
Admin console at:  http://localhost:3018/admin
GraphQL API at:  http://localhost:3018/graphql
✔ Successfully connected to database!
ℹ Checking Install...
ℹ Checking Base Content...
✔ Base Content Verified!
✔ Install Verified!

**Comment by lane711** [comment]
ok, sorry I think I see the issue - there was a bug, if you pull latest on master, this should be resolved
