### ISSUE TITLE
DeprecationWarning: Mongoose

### ISSUE THREAD

**Issue by lane711** [lane711/sonicjs#67]
(node:2107) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify

Need to determine the source of this and fix. The may be coming from one of the project dependencies

**Comment by Kumar85** [comment]
You can use `mongoose.set('useFindAndModify', false)` before mongoose.connect()  or `mongoose.connect(url, { useFindAndModify: false })` to remove this Warning
