### ISSUE TITLE
node error while trying to edit a content

### ISSUE THREAD

**Issue by vahidreza** [lane711/sonicjs#86]
loaded up the contents section in the admin area and clicked on the edit button of the "section 1" content item and got this:

(node:30411) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'components' of null
    at Object.exports.getFormComponents (/Users/vahidreza/Downloads/sonicjs/server/services/form.service.js:247:41)
    at Object.exports.getFormJson (/Users/vahidreza/Downloads/sonicjs/server/services/form.service.js:200:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30411) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:30411) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lane711** [comment]
Closing due to no response and no other reports of this issue
